version: "3"

tasks:
  build:
    desc: Build the app
    cmds:
      - GOFLAGS=-mod=mod go build -o bin/debug/ cmd/shorturl/main.go
  build-release:
    desc: Build the app without debug information
    cmds:
      -  GOFLAGS=-mod=mod go build -ldflags "-s -w" -o bin/release/ cmd/shorturl/main.go
  run:
    desc: Run the app
    cmds:
      - GOFLAGS=-mod=mod go run cmd/shorturl/main.go
  run-release:
    desc: Run the app without debug information
    cmds:
      - GOFLAGS=-mod=mod go run -ldflags "-s -w" cmd/shorturl/main.go
  test:
    desc: Run the tests with coverage
    cmds:
      -  go test ./... -cover
