version: "3"

tasks:
  build:
    desc: Build the app
    cmds:
      - GOFLAGS=-mod=mod go build -o bin/debug/ main.go
  build-release:
    desc: Builds the release version of the app
    cmds:
      -  GOFLAGS=-mod=mod go build -ldflags "-s -w" -o bin/release/ main.go
  run:
    desc: Run the app
    cmds:
      - GOFLAGS=-mod=mod go run main.go
