name: Go

on: [workflow_dispatch, push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Build
        run: task build-release

      - name: Test
        run: task test
